- hosts: localhost
  become: yes
  roles:
    - general
    - development
    - angstwad.docker_ubuntu
    - geerlingguy.nodejs
  vars:
    ansible_user: ando
    docker_group_members: ando
    nodejs_version: "6.x"
    nodejs_npm_global_packages:
      - name: jslint
      - name: bower
